services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"  # Access Open WebUI at http://localhost:3000
    environment:
      - OLLAMA_BASE_URL=http://docker.vashdima.com:11434
    volumes:
      - open-webui-data:/app/backend/data
    restart: unless-stopped

volumes:
  open-webui-data: