version: '3.8'

services:
  ollama:
    image: ollama-custom
    container_name: ollama-custom
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_MODELS=/home/ollama/.ollama/models
      - OLLAMA_DEBUG=INFO
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=1
    volumes:
      # Optional: Mount a volume if you want to persist additional models
      # - ./ollama-data:/home/ollama/.ollama
      - /tmp:/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge 