version: '3.8'

services:
  ollama:
    image: ollama-custom
    platform: linux/amd64  # Required for Apple Silicon emulation
    container_name: ollama-custom
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_MODELS=/home/ollama/.ollama/models
      - OLLAMA_DEBUG=INFO
      # Conservative settings for emulation
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_LOADED_MODELS=1
    volumes:
      - /tmp:/tmp
      # Optional: persistent storage for additional models
      # - ./ollama-data:/home/ollama/.ollama
    restart: unless-stopped
    # Resource limits for emulation
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge 